//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMyPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hang
    {
        public int MaHang { get; set; }
        public string TenHang { get; set; }
        public string HinhAnh { get; set; }
    }
}
