//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMyPham.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CuaHangBanMyPhamEntities : DbContext
    {
        public CuaHangBanMyPhamEntities()
            : base("name=CuaHangBanMyPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual ObjectResult<GetCTHoaDon_Result> GetCTHoaDon(Nullable<int> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCTHoaDon_Result>("GetCTHoaDon", maHDParameter);
        }
    
        public virtual ObjectResult<GetHoaDons_Result> GetHoaDons()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHoaDons_Result>("GetHoaDons");
        }
    
        public virtual ObjectResult<GetHoaDonsTaiKhoan_Result> GetHoaDonsTaiKhoan(string tenTK)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHoaDonsTaiKhoan_Result>("GetHoaDonsTaiKhoan", tenTKParameter);
        }
    
        public virtual ObjectResult<GetSanPhamID_Result> GetSanPhamID(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSanPhamID_Result>("GetSanPhamID", maSPParameter);
        }
    
        public virtual ObjectResult<GetSanPhams_Result> GetSanPhams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSanPhams_Result>("GetSanPhams");
        }
    
        public virtual ObjectResult<GetSanPhamTheoHang_Result> GetSanPhamTheoHang(Nullable<int> maHang)
        {
            var maHangParameter = maHang.HasValue ?
                new ObjectParameter("MaHang", maHang) :
                new ObjectParameter("MaHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSanPhamTheoHang_Result>("GetSanPhamTheoHang", maHangParameter);
        }
    }
}
